retrieve_product_info_task:
  description: >
    Analyze the user query "{user_query}" to identify the product being discussed.
    Retrieve relevant product information from storage, including product name,
    category, features, specifications, target audience, and any available templates.
    If multiple similar products exist, select the most relevant one based on the query.
  expected_output: >
    A comprehensive JSON object containing all relevant product information, including
    product name, category, key features, specifications, target audience, pricing,
    and any applicable templates. The information should be structured and complete
    enough to generate a detailed product description.

generate_description_task:
  description: >
    Using the product information provided, generate a detailed and engaging product
    description that highlights the key features, benefits, and unique selling points.
    The description should be tailored to the target audience and incorporate relevant
    SEO keywords. If a template is provided, use it as a guide while ensuring the
    description remains original and compelling.
  expected_output: >
    A well-structured product description of 300-500 words that effectively communicates
    the product's value proposition. The description should include a compelling headline,
    an engaging introduction, detailed feature descriptions with benefits, and a strong
    conclusion with a call-to-action. The content should be SEO-optimized and formatted
    in markdown.

refine_description_task:
  description: >
    Review and refine the generated product description to enhance its effectiveness.
    Focus on optimizing the tone to match the target audience, ensuring proper keyword
    placement and density for SEO, strengthening the call-to-action, and improving
    overall readability and persuasiveness. Maintain the original structure while
    making targeted improvements.
  expected_output: >
    A refined and polished product description that maintains the core information
    while featuring improved tone, better keyword integration, stronger call-to-action,
    and enhanced readability. The refinements should be subtle but impactful, elevating
    the quality of the description without completely rewriting it. The final output
    should be in markdown format.
